/* Generated By:JavaCC: Do not edit this line. POParserConstants.java */
package net.sf.tweety.preferences.io;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface POParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRA = 2;
  /** RegularExpression Id. */
  int RBRA = 3;
  /** RegularExpression Id. */
  int ELEMENT = 4;
  /** RegularExpression Id. */
  int REL = 5;
  /** RegularExpression Id. */
  int EOL = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"{\"",
    "\"}\"",
    "<ELEMENT>",
    "<REL>",
    "<EOL>",
    "\",\"",
  };

}
