/* Generated By:JJTree: Do not edit this line. ASTClingoID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.tweetyproject.lp.asp.parser;

public
class ASTClingoID extends SimpleNode {
	
  protected String name;
	
  public ASTClingoID(int id) {
    super(id);
  }

  public ASTClingoID(ASPParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ASPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public void name(String image) {
	this.name = image;
  }
  
}
/* JavaCC - OriginalChecksum=2a889a25e37f092ba31f1f3d0664f142 (do not edit this line) */
