/*
 *  This file is part of "TweetyProject", a collection of Java libraries for
 *  logical aspects of artificial intelligence and knowledge representation.
 *
 *  TweetyProject is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License version 3 as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *  Copyright 2016 The TweetyProject Team <http://tweetyproject.org/contact/>
 */
/* Generated By:JavaCC: Do not edit this line. RpclCondensedProbabilityDistributionParserConstants.java */
package org.tweetyproject.logics.rpcl.parser.rpclcondensedprobabilitydistributionparser;


/*
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RpclCondensedProbabilityDistributionParserConstants {

  /* End of File. */
  int EOF = 0;
  /* RegularExpression Id. */
  int STRUCTURENAME = 5;
  /* RegularExpression Id. */
  int MULTIPLICATOR = 6;
  /* RegularExpression Id. */
  int PROBABILITY = 7;

  /* Lexical state. */
  int DEFAULT = 0;

  /* Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<STRUCTURENAME>",
    "<MULTIPLICATOR>",
    "<PROBABILITY>",
    "\"=\"",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\"<\"",
    "\">\"",
  };

}
