/* Generated By:JavaCC: Do not edit this line. RpclProbabilityDistributionParserConstants.java */
package net.sf.tweety.logics.rpcl.parser.rpclprobabilitydistributionparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RpclProbabilityDistributionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRUCTURENAME = 5;
  /** RegularExpression Id. */
  int PROBABILITY = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<STRUCTURENAME>",
    "<PROBABILITY>",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
  };

}
