/* Generated By:JavaCC: Do not edit this line. ASPCore2ParserTreeConstants.java Version 5.0 */
/*
 *  This file is part of "TweetyProject", a collection of Java libraries for
 *  logical aspects of artificial intelligence and knowledge representation.
 *
 *  TweetyProject is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License version 3 as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *  Copyright 2018 The TweetyProject Team <http://tweetyproject.org/contact/>
 */
package net.sf.tweety.lp.asp.parser;
public interface ASPCore2ParserTreeConstants
{
  public int JJTANSWERSET = 0;
  public int JJTPROGRAM = 1;
  public int JJTRULELIST = 2;
  public int JJTQUERY = 3;
  public int JJTRULE = 4;
  public int JJTHEAD = 5;
  public int JJTBODYLIST = 6;
  public int JJTBODY = 7;
  public int JJTHEADELEMENTSLIST = 8;
  public int JJTCHOICE = 9;
  public int JJTCHOICEELEMENTLIST = 10;
  public int JJTCHOICEELEMENT = 11;
  public int JJTAGGREGATE = 12;
  public int JJTAGGRELEMENTLIST = 13;
  public int JJTAGGRELEMENT = 14;
  public int JJTAGGRFUNC = 15;
  public int JJTOPT = 16;
  public int JJTOPTELEMENTLIST = 17;
  public int JJTOPTELEMENT = 18;
  public int JJTOPTFUNC = 19;
  public int JJTWEIGHT = 20;
  public int JJTNAFLITERALLIST = 21;
  public int JJTNAFLITERAL = 22;
  public int JJTATOM = 23;
  public int JJTBUILTINATOM = 24;
  public int JJTBINOP = 25;
  public int JJTTERMLIST = 26;
  public int JJTTERM = 27;
  public int JJTARITERM = 28;
  public int JJTARITHOP = 29;
  public int JJTNUMBER = 30;
  public int JJTVAR = 31;
  public int JJTID = 32;
  public int JJTSTRING = 33;


  public String[] jjtNodeName = {
    "AnswerSet",
    "Program",
    "RuleList",
    "Query",
    "Rule",
    "Head",
    "BodyList",
    "Body",
    "HeadElementsList",
    "Choice",
    "ChoiceElementList",
    "ChoiceElement",
    "Aggregate",
    "AggrElementList",
    "AggrElement",
    "AggrFunc",
    "Opt",
    "OptElementList",
    "OptElement",
    "OptFunc",
    "Weight",
    "NAFLiteralList",
    "NAFLiteral",
    "Atom",
    "BuiltInAtom",
    "Binop",
    "TermList",
    "Term",
    "AriTerm",
    "Arithop",
    "Number",
    "Var",
    "ID",
    "String",
  };
}
/* JavaCC - OriginalChecksum=4d09cb3675c659db72710b3590fdbd7a (do not edit this line) */
