/* Generated By:JavaCC: Do not edit this line. ASPCore2ParserVisitor.java Version 5.0 */
/*
 *  This file is part of "TweetyProject", a collection of Java libraries for
 *  logical aspects of artificial intelligence and knowledge representation.
 *
 *  TweetyProject is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License version 3 as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *  Copyright 2018 The TweetyProject Team <http://tweetyproject.org/contact/>
 */
package net.sf.tweety.lp.asp.parser;
public interface ASPCore2ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTAnswerSet node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTRuleList node, Object data);
  public Object visit(ASTQuery node, Object data);
  public Object visit(ASTRule node, Object data);
  public Object visit(ASTHead node, Object data);
  public Object visit(ASTBodyList node, Object data);
  public Object visit(ASTBody node, Object data);
  public Object visit(ASTHeadElementsList node, Object data);
  public Object visit(ASTChoice node, Object data);
  public Object visit(ASTChoiceElementList node, Object data);
  public Object visit(ASTChoiceElement node, Object data);
  public Object visit(ASTAggregate node, Object data);
  public Object visit(ASTAggrElementList node, Object data);
  public Object visit(ASTAggrElement node, Object data);
  public Object visit(ASTAggrFunc node, Object data);
  public Object visit(ASTOpt node, Object data);
  public Object visit(ASTOptElementList node, Object data);
  public Object visit(ASTOptElement node, Object data);
  public Object visit(ASTOptFunc node, Object data);
  public Object visit(ASTWeight node, Object data);
  public Object visit(ASTNAFLiteralList node, Object data);
  public Object visit(ASTNAFLiteral node, Object data);
  public Object visit(ASTAtom node, Object data);
  public Object visit(ASTBuiltInAtom node, Object data);
  public Object visit(ASTBinop node, Object data);
  public Object visit(ASTTermList node, Object data);
  public Object visit(ASTTerm node, Object data);
  public Object visit(ASTAriTerm node, Object data);
  public Object visit(ASTArithop node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTVar node, Object data);
  public Object visit(ASTID node, Object data);
  public Object visit(ASTString node, Object data);
}
/* JavaCC - OriginalChecksum=ffbcf8483d616feef5095b14c5aa1993 (do not edit this line) */
