/* Generated By:JJTree: Do not edit this line. ASTArithmeticInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sf.tweety.lp.asp.parser;

public
class ASTArithmeticInteger extends SimpleNode {
	protected String variableName;
  public ASTArithmeticInteger(int id) {
    super(id);
  }

  public ASTArithmeticInteger(ASPParser p, int id) {
    super(p, id);
  }

  public void setVariableName(String variableName) {
	  this.variableName = variableName;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ASPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8e49f05d5a281a10ce9ae32f7125acfc (do not edit this line) */
