/* Generated By:JJTree: Do not edit this line. ASTCompareOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sf.tweety.lp.asp.parser;

public
class ASTCompareOp extends SimpleNode {
  protected String operator;
	
	public ASTCompareOp(int id) {
    super(id);
  }

  public ASTCompareOp(ASPParser p, int id) {
    super(p, id);
  }

  public void setOperator(String operator) {
	  this.operator = operator;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ASPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a9c363eaeb5c34b8844c2206ae3bc60 (do not edit this line) */
