/* Generated By:JJTree: Do not edit this line. ASTListTail.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sf.tweety.lp.asp.parser;

public
class ASTListTail extends SimpleNode {
  protected String variableName = null;
	public ASTListTail(int id) {
    super(id);
  }

  public ASTListTail(ASPParser p, int id) {
    super(p, id);
  }

  public void setVariableName(String name) {
	  this.variableName = name;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ASPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd968cfb3d6f4e33cc4aa1a4d6790fed (do not edit this line) */
