/* Generated By:JJTree: Do not edit this line. ASTNumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sf.tweety.lp.asp.parser;

public
class ASTNumber extends SimpleNode {
  int number;
	public ASTNumber(int id) {
    super(id);
  }

  public ASTNumber(ASPParser p, int id) {
    super(p, id);
  }

  public void setNumber(String number) {
	  this.number = Integer.parseInt(number);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ASPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fcf7c3b5bbb0464eedfb45a9991337f0 (do not edit this line) */
